version: '3'

services:
  nodejs:
    image: 241019962020/superassistant-node:65
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: 241019962020/superassistant-node:65
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email svatsa159@gmail.com --agree-tos --no-eff-email --staging -d app2.superassistant.io  -d www.app2.superassistant.io

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
